apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xbk8ax9r2-nodejs
  janus-idp.io/tekton: xbk8ax9r2-nodejs
  backstage.io/kubernetes-id: xbk8ax9r2-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xbk8ax9r2-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
